name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: {}
defaults:
  run:
    shell: bash -euo pipefail {0}
jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container: swift:6.2
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: |
            ~/.cache/org.swift.swiftpm
            ~/.swiftpm
            .build
          key: ${{ runner.os }}-swiftpm-6.2-${{ hashFiles('Package.resolved') }}
          restore-keys: ${{ runner.os }}-swiftpm-6.2-
      - run: swift --version
      - run: swift build --build-tests --disable-xctest --enable-code-coverage
      - run: swift test --skip-build --disable-xctest --enable-code-coverage
      - run: llvm-cov export --format=lcov .build/debug/html-entity-coderPackageTests.xctest --instr-profile=.build/debug/codecov/default.profdata --ignore-filename-regex=".build|Tests" > coverage_report.lcov
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: coverage-report-lcov
          path: coverage_report.lcov
  comment-test:
    needs: test
    runs-on: ubuntu-24.04-arm
    continue-on-error: true
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: coverage-report-lcov
      - uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9  # v1.5.1
  lint:
    runs-on: ubuntu-24.04-arm
    container: swift:6.2
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: swift format lint -rsp .
  yamllint:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: yamllint --version
      - run: yamllint --strict --config-file .yamllint.yml .
